name: fluth
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  json_annotation: ^4.6.0
  http: ^0.13.4
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - assets/icons/cylinder.svg
    - assets/icons/trapeziom.svg
    - assets/icons/trapesium.jpg.webp
