// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMP8VKHlB3KCxQWewDliZBCcMwICyfEdw',
    appId: '1:1019616162586:web:b1f21bcf8cf7e35743f2a3',
    messagingSenderId: '1019616162586',
    projectId: 'tpm-app-e0be2',
    authDomain: 'tpm-app-e0be2.firebaseapp.com',
    storageBucket: 'tpm-app-e0be2.appspot.com',
    measurementId: 'G-M6NH40QW9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEYuGL3crM53KGVlYx44xU0hWULGR2ZBs',
    appId: '1:1019616162586:android:24b076bbbebd43df43f2a3',
    messagingSenderId: '1019616162586',
    projectId: 'tpm-app-e0be2',
    storageBucket: 'tpm-app-e0be2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-yWZZ5LXlLFrmvjlyATZpoYMTVE7tVd4',
    appId: '1:1019616162586:ios:a5df8789ed00902c43f2a3',
    messagingSenderId: '1019616162586',
    projectId: 'tpm-app-e0be2',
    storageBucket: 'tpm-app-e0be2.appspot.com',
    iosClientId: '1019616162586-d7i68rfbse7fv7cj5qs841sekg2oh5lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-yWZZ5LXlLFrmvjlyATZpoYMTVE7tVd4',
    appId: '1:1019616162586:ios:a5df8789ed00902c43f2a3',
    messagingSenderId: '1019616162586',
    projectId: 'tpm-app-e0be2',
    storageBucket: 'tpm-app-e0be2.appspot.com',
    iosClientId: '1019616162586-d7i68rfbse7fv7cj5qs841sekg2oh5lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluth',
  );
}
